/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paint;

import java.awt.Color;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import paint.models.Paint;
import paint.models.Tool;

/**
 *
 * @author Rémi JARA
 */
public class Inspecteur extends javax.swing.JFrame {
    private TableModelInspector model;
    /**
     * Creates new form Inspecteur
     */
    public Inspecteur() {
        initComponents();
        //make the propertiesPanel inisible
        propertiesPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightPanel = new javax.swing.JPanel();
        propertiesPanel = new javax.swing.JPanel();
        infos = new javax.swing.JPanel();
        formeLabel = new javax.swing.JLabel();
        comboBoxForme = new javax.swing.JComboBox<Tool>();
        couleurLabel = new javax.swing.JLabel();
        couleurProperties = new javax.swing.JPanel();
        lisseLabel = new javax.swing.JLabel();
        lisseCheckBox = new javax.swing.JCheckBox();
        tailleLabel = new javax.swing.JLabel();
        tailleSpinner = new javax.swing.JSpinner();
        xLabel = new javax.swing.JLabel();
        xSpinner = new javax.swing.JSpinner();
        yLabel = new javax.swing.JLabel();
        ySpinner = new javax.swing.JSpinner();
        supprimerPoint = new javax.swing.JButton();
        modifierPoint = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        rightPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        rightPanel.setMaximumSize(new java.awt.Dimension(215, 362));
        rightPanel.setMinimumSize(new java.awt.Dimension(215, 362));
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.PAGE_AXIS));

        propertiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties"));
        propertiesPanel.setPreferredSize(new java.awt.Dimension(211, 358));

        infos.setLayout(new java.awt.GridLayout(6, 2, -100, 5));

        formeLabel.setText("Forme:");
        infos.add(formeLabel);

        comboBoxForme.setModel(new ComboBoxModel());
        infos.add(comboBoxForme);

        couleurLabel.setText("Couleur:");
        infos.add(couleurLabel);

        couleurProperties.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        couleurProperties.setPreferredSize(new java.awt.Dimension(102, 40));
        couleurProperties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout couleurPropertiesLayout = new javax.swing.GroupLayout(couleurProperties);
        couleurProperties.setLayout(couleurPropertiesLayout);
        couleurPropertiesLayout.setHorizontalGroup(
            couleurPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        couleurPropertiesLayout.setVerticalGroup(
            couleurPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        infos.add(couleurProperties);

        lisseLabel.setText("Lisse:");
        infos.add(lisseLabel);
        infos.add(lisseCheckBox);

        tailleLabel.setText("Taille:");
        infos.add(tailleLabel);

        tailleSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        infos.add(tailleSpinner);

        xLabel.setText("X:");
        infos.add(xLabel);
        infos.add(xSpinner);

        yLabel.setText("Y:");
        infos.add(yLabel);
        infos.add(ySpinner);

        supprimerPoint.setText("Supprimer");
        supprimerPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerPointActionPerformed(evt);
            }
        });

        modifierPoint.setText("Modifier");
        modifierPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierPointActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(propertiesPanelLayout.createSequentialGroup()
                        .addComponent(supprimerPoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifierPoint)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(propertiesPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(infos, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, propertiesPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprimerPoint)
                    .addComponent(modifierPoint))
                .addGap(97, 97, 97))
            .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(propertiesPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(infos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        rightPanel.add(propertiesPanel);

        getContentPane().add(rightPanel, java.awt.BorderLayout.LINE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                propertiesPanel.setVisible(true);
                //get the selected row index
                int row = jTable1.getSelectedRow();
                if(row == -1){
                    return;
                }
                //get the paint in the list at the selected row
                Paint p = model.getPaints().get(row);
                //set the selected row data to the properties panel
                comboBoxForme.setSelectedItem(p.getTool());
                couleurProperties.setBackground(p.getColor());
                lisseCheckBox.setSelected(p.isSmooth());
                tailleSpinner.setValue(p.getWidth());
                xSpinner.setValue(p.getX());
                ySpinner.setValue(p.getY());
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //uncheck the static menuitemcheckbox in ardoise
        Ardoise.getInspecteur().setSelected(false);
    }//GEN-LAST:event_formWindowClosing

    private void supprimerPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerPointActionPerformed
        int row = jTable1.getSelectedRow();
        System.out.print(row);
        this.model.deletePoint(row);
        this.model.getSlate().revalidate();
        this.model.getSlate().repaint();
    }//GEN-LAST:event_supprimerPointActionPerformed

    private void modifierPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierPointActionPerformed
        int row = jTable1.getSelectedRow();
        //get all infos selected in infos panel : forme, couleur, epaisseur, x, y, lisse?
        Tool tool = (Tool) this.comboBoxForme.getSelectedItem();
        Color color = this.couleurProperties.getBackground();
        boolean lisse = this.lisseCheckBox.isSelected();
        int taille = (int) this.tailleSpinner.getValue();
        int x = (int) this.xSpinner.getValue();
        int y = (int) this.ySpinner.getValue();
        //create a new Paint object with these infos
        Paint paint = new Paint(x, y, taille, lisse, color,  tool);
        this.model.modifPoint(row, paint);
        //repaint the slate
        this.model.getSlate().repaint();
    }//GEN-LAST:event_modifierPointActionPerformed

    private void mouseClickedActionPerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedActionPerformed
        //open dialog color chooser
        Color color = JColorChooser.showDialog(this, "Choose a color", this.couleurProperties.getBackground());
        //set the color chooser color to the color of the properties panel
        this.couleurProperties.setBackground(color);
    }//GEN-LAST:event_mouseClickedActionPerformed

    public void setVisible(TableModelInspector model){
        this.jTable1.setModel(model);
        this.model = model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Tool> comboBoxForme;
    private javax.swing.JLabel couleurLabel;
    private javax.swing.JPanel couleurProperties;
    private javax.swing.JLabel formeLabel;
    private javax.swing.JPanel infos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox lisseCheckBox;
    private javax.swing.JLabel lisseLabel;
    private javax.swing.JButton modifierPoint;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton supprimerPoint;
    private javax.swing.JLabel tailleLabel;
    private javax.swing.JSpinner tailleSpinner;
    private javax.swing.JLabel xLabel;
    private javax.swing.JSpinner xSpinner;
    private javax.swing.JLabel yLabel;
    private javax.swing.JSpinner ySpinner;
    // End of variables declaration//GEN-END:variables

    public class ComboBoxModel extends DefaultComboBoxModel<Tool>{
        public ComboBoxModel(){
            super(new Tool[]{Tool.SQUARE, Tool.ROUND});
        }
    }
}
